name: Backend CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yml"
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Optional linters (skip if not installed)
          if python -c "import flake8" 2>/dev/null; then flake8 || true; fi

      - name: Syntax check
        working-directory: backend
        run: python -m compileall -q .

      - name: Start FastAPI (smoke) / Skip (no tests)
        if: false
        run: echo "Add pytest here if tests are added later"