name: Frontend CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-ci.yml"
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: frontend/yarn.lock

      - name: Install deps
        working-directory: frontend
        run: yarn install --frozen-lockfile

      - name: Lint (if configured)
        working-directory: frontend
        run: |
          if yarn run -s lint >/dev/null 2>&1; then
            yarn lint
          else
            echo "No lint script. Skipping."
          fi

      - name: Build
        working-directory: frontend
        env:
          REACT_APP_BACKEND_URL: ${{ secrets.REACT_APP_BACKEND_URL || 'http://localhost:8001' }}
        run: yarn build