name: Frontend CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-ci.yml"
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: frontend/yarn.lock

      - name: Set REACT_APP_BACKEND_URL (default if secret not set)
        run: |
          if [ -z "${{ secrets.REACT_APP_BACKEND_URL }}" ]; then
            echo "REACT_APP_BACKEND_URL=http://localhost:8001" >> $GITHUB_ENV
          else
            echo "REACT_APP_BACKEND_URL=${{ secrets.REACT_APP_BACKEND_URL }}" >> $GITHUB_ENV
          fi

      - name: Install deps
        working-directory: frontend
        run: yarn install --frozen-lockfile

      - name: Lint (skip if not configured)
        working-directory: frontend
        run: |
          if yarn run -s lint >/dev/null 2>&1; then
            yarn lint
          else
            echo "No lint script. Skipping."
          fi

      - name: Build
        working-directory: frontend
        env:
          REACT_APP_BACKEND_URL: ${{ env.REACT_APP_BACKEND_URL }}
          CI: false
        run: yarn build